let ListProduct = [{
        CPU: "Apple A15 Bionic",
        RAM: "6 GB",
        SIM: "1 Nano SIM & 1 eSIMHỗ trợ 5G",
        battery: "3095 mAh20 W",
        color: "Bạc,Xanh, Xám",
        front_camera: "12 MP",
        img: "https://cdn.tgdd.vn/Products/Images/42/230521/Slider/iphone-13-promax-1020x570.jpg",
        manufacturer: "Apple",
        memory: "128GB,256GB,512GB,1TB",
        name: "Điện thoại iPhone 13 Pro 128GB",
        price: "29.990.000₫",
        rear_camera: "3 camera 12 MP",
        resolution: "OLED6.1\"Super Retina XDR",
        system: "iOS 15",
        type_product: "Smart phone",
    },
    {
        CPU: "Apple A14 Bionic",
        RAM: "6 GB",
        SIM: "1 Nano SIM & 1 eSIMHỗ trợ 5G",
        battery: "2815 mAh20 W",
        color: "Bạc,Xanh, Xám,Vàng đồng",
        front_camera: "12 MP",
        img: "https://cdn.tgdd.vn/Products/Images/42/213032/Slider/iphone-12-pro-thumbv-780x433-1.jpg",
        manufacturer: "Apple",
        memory: "128GB,256GB,512GB",
        name: "Điện thoại iPhone 12 Pro 128GB",
        price: "28.990.000₫",
        rear_camera: "3 camera 12 MP",
        resolution: "OLED6.1\"Super Retina XDR",
        system: "iOS 14",
        type_product: "Smart phone",
    },
    {
        CPU: "Exynos 2100",
        RAM: "12 GB",
        SIM: "2 Nano SIM hoặc 1 Nano SIM + 1 eSIMHỗ trợ 5G",
        battery: "5000 mAh25 W",
        color: "Đen,Bạc",
        front_camera: "40 MP",
        img: "https://cdn.tgdd.vn/Products/Images/42/226316/Slider/samsung-galaxy-s21-ultra-thumbvideo-780x433.jpg",
        manufacturer: "Samsung",
        memory: "128GB",
        name: "Điện thoại Samsung Galaxy S21 Ultra 5G 128GB",
        price: "21.990.000₫ ",
        rear_camera: "Chính 108 MP & Phụ 12 MP, 10 MP, 10 MP",
        resolution: "Dynamic AMOLED 2X6.8\"Quad HD+ (2K+)",
        system: "Android 11",
        type_product: "Smart phone",
    },
    {
        CPU: "Snapdragon 888",
        RAM: "12 GB",
        SIM: "2 Nano SIMHỗ trợ 5G",
        battery: "4400 mAh25 W",
        color: "Đen,Bạc,Xanh rêu",
        front_camera: "10 MP & 4 MP",
        img: "https://cdn.tgdd.vn/Products/Images/42/248284/Slider/samsung-galaxy-z-fold-3-slider-tong-quan-1020x570.jpg",
        manufacturer: "Samsung",
        memory: "256GB,512GB",
        name: "Điện thoại Samsung Galaxy Z Fold3 5G 512GB",
        price: "44.990.000₫",
        rear_camera: "3 camera 12 MP",
        resolution: "Dynamic AMOLED 2XChính 7.6\" & Phụ 6.2\"Full HD+",
        system: "Android 11",
        type_product: "Smart phone",
    },
    {
        CPU: "Snapdragon 888",
        RAM: "8 GB",
        SIM: "1 Nano SIM & 1 eSIMHỗ trợ 5G",
        battery: "3300 mAh15 W",
        color: "Đen,Bạc,Xanh rêu,Kem",
        front_camera: "10 MP",
        img: "https://cdn.tgdd.vn/Products/Images/42/248283/Slider/samsung-galaxy-z-flip3-5g-256gb-230821-04105416.jpg",
        manufacturer: "Samsung",
        memory: "128GB,256GB",
        name: "Điện thoại Samsung Galaxy Z Flip3 5G 256GB",
        price: "26.990.000₫",
        rear_camera: "2 camera 12 MP",
        resolution: "Dynamic AMOLED 2XChính 6.7\" & Phụ 1.9\"Full HD+",
        system: "Android 11",
        type_product: "Smart phone",
    },
    {
        CPU: "Snapdragon 778G 5G 8 nhân",
        RAM: "8 GB",
        SIM: "2 Nano SIMHỗ trợ 5G",
        battery: "4500 mAh25 W",
        color: "Đen,Bạc,Xanh rêu,Kem",
        front_camera: "32 MP",
        img: "https://cdn.tgdd.vn/Products/Images/42/247507/Slider/vi-vn-samsung-galaxy-a52s-5g-slider-tong-quan.jpg",
        manufacturer: "Samsung",
        memory: "128GB,256GB",
        name: "Điện thoại Samsung Galaxy A52s 5G",
        price: "10.990.000₫",
        rear_camera: "Chính 64 MP & Phụ 12 MP, 5 MP, 5 MP",
        resolution: "Super AMOLED6.5\"Full HD+",
        system: "Android 11",
        type_product: "Smart phone",
    },
    {
        CPU: "Exynos 2100",
        RAM: "8 GB",
        SIM: "2 Nano SIM hoặc 1 Nano SIM + 1 eSIMHỗ trợ 5G",
        battery: "4000 mAh, 25 W",
        color: "Tím,Trắng,Xám",
        front_camera: "10 MP",
        img: "https://cdn.tgdd.vn/Products/Images/42/220833/Slider/samsung-galaxy-s21-5g-thumb-video-780x433.jpg",
        manufacturer: "Samsung",
        memory: "128GB,256GB",
        name: "Điện thoại Samsung Galaxy S21 5G",
        price: "14.990.000₫",
        rear_camera: "Chính 12 MP & Phụ 64 MP, 12 MP",
        resolution: "Dynamic AMOLED 2X6.2\"Full HD+",
        system: "Android 11",
        type_product: "Smart phone",
    },
    {
        CPU: "Apple A14 Bionic",
        RAM: "4 GB",
        SIM: "1 Nano SIM & 1 eSIMHỗ trợ 5G",
        battery: "2227 mAh20 W",
        color: "Tím,Đen,Đỏ,Xanh Dương,Xanh lá,Trắng",
        front_camera: "12 MP",
        img: "https://cdn.tgdd.vn/Products/Images/42/225380/Slider/iphone-12-mini-thumbvideo-780x433-1.jpg",
        manufacturer: "Apple",
        memory: "64GB,128GB,256GB",
        name: "Điện thoại iPhone 12 mini 64GB",
        price: "18.990.000₫",
        rear_camera: "2 camera 12 MP",
        resolution: "OLED5.4\"Super Retina XDR",
        system: "iOS 14",
        type_product: "Smart phone",
    },
    {
        CPU: "Apple A12 Bionic",
        RAM: "3 GB",
        SIM: "1 Nano SIM & 1 eSIMHỗ trợ 4G",
        battery: "2942 mAh15 W",
        color: "Tím,Đen,Đỏ,Xanh Dương,Xanh lá,Trắng",
        front_camera: "7 MP",
        img: "https://cdn.tgdd.vn/Products/Images/42/190325/Slider/-iphone-xr-thumbvideo.jpg",
        manufacturer: "Apple",
        memory: "64GB,128GB",
        name: "Điện thoại iPhone XR 64GB",
        price: "13.490.000₫ ",
        rear_camera: "12 MP",
        resolution: "IPS LCD6.1\"Liquid Retina",
        system: "iOS 14",
        type_product: "Smart phone",
    },
    {
        CPU: "Apple A13 Bionic",
        RAM: "3 GB",
        SIM: "1 Nano SIM & 1 eSIMHỗ trợ 4G",
        battery: "2942 mAh15 W",
        color: "Trắng,Đen,Đỏ",
        front_camera: "7 MP",
        img: "https://cdn.tgdd.vn/Products/Images/42/230410/Slider/iphone-se-64gb-2020-hop-moi-101120-0837010.jpg",
        manufacturer: "Apple",
        memory: "64GB,128GB",
        name: "Điện thoại iPhone SE 64GB (2020) (Hộp mới)",
        price: "11.990.000₫",
        rear_camera: "12 MP",
        resolution: "IPS LCD4.7\"Retina HD",
        system: "iOS 14",
        type_product: "Smart phone",
    }
]

let page = document.getElementById('product_list');
let id

function list() {
    for (let i = 0; i < ListProduct.length; i++) {
        page.innerHTML += `
            <div class="item"  onclick="click()">
                <div class="img_item">
                    <img src="` + ListProduct[i].img + `">
                </div>
                <p id="name">` + ListProduct[i].name + `</p>
                <h3>` + ListProduct[i].price + `</h3>
                <p>Quà tặng 100.000đ</p>
                <div style="padding: 20px;">
                    <div>+</div>
                    <span>So sánh</span>
                </div>
            </div> 
        `
        id = ListProduct[i].name
    }
}

list()

let name_product = document.getElementById('name');

let body = document.getElementById('body');

function click() {

}


// đóng mở modal
var button_exist = document.querySelector('.header-search-exist');
button_exist.onclick = function() {
    document.querySelector('.modal').classList.add('active');
}

var button_close_modal = document.querySelector('.form-select-heading-close');
button_close_modal.onclick = function() {
    document.querySelector('.modal').classList.remove('active');
}

document.querySelector('.modal').onclick = function() {
    document.querySelector('.modal').classList.remove('active');
}

document.querySelector('.form-select').addEventListener('click', function(event) {
    event.stopPropagation();
})